name: "Feature Request"
description: "Suggest an idea for this project"
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: "### 🚀 Please fill out the following details for your feature request"

  - type: input
    id: problem
    attributes:
      label: "Problem Area"
      description: "Is your feature request related to a problem? Please describe."
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the solution you'd like"
      placeholder: "A clear and concise description of what you want to happen"

  - type: textarea
    id: solution
    attributes:
      label: "Workarounds"
      description: "Describe alternatives you've considered"
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."

  - type: dropdown
    id: category
    attributes:
      label: "Feature Type"
      description: "What type of feature is this?"
      options:
        - "New API"
        - "UI/UX Improvement"
        - "Performance Enhancement"
        - "Security Improvement"
        - "Other"

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any extra details? Screenshots? Links?"
      placeholder: "Add any other context or screenshots about the feature request here."