services:
  firesky-frontend:
    image: f1r3flyindustries/firesky-frontend
    ports:
      - 8100:8100
    command: /usr/bin/bskyweb serve

  postgres-ts-backend:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: password
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    command: redis-server --save 60 1 --loglevel warning
    tmpfs:
      - /data

  firesky-ts:
    image: f1r3flyindustries/firesky-ts
    environment:
      PGPORT: 5432
      PGHOST: postgres-ts-backend
      PGUSER: pg
      PGPASSWORD: password
      PGDATABASE: postgres
      DB_POSTGRES_URL: postgresql://pg:password@postgres-ts-backend:5432/postgres
      REDIS_HOST: redis-1:6379
      NODE_ENV: development
      SECOND_NETWORK: 1
      ALTERNATIVE_PDS_HOST: pds-1
      ALTERNATIVE_PDS_HOST2: events-listen
      LOG_ENABLED: true
    depends_on:
      - postgres-ts-backend
      - redis

  postgresql-rs-1:
    image: postgres:17-bookworm
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  postgresql-rs-2:
    image: postgres:17-bookworm
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    tmpfs:
      - /data
    command: server /data --console-address ":9001"

  pds-1:
    image: f1r3flyindustries/firesky-rs
    ports:
      - 2583:2583
    env_file:
      - .env-1
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_ENDPOINT: http://minio:9000
      AWS_SECRET_ACCESS_KEY: minioadmin
      PDS_DEV_MODE: true
      PDS_DID_PLC_URL: http://firesky-ts:2582
      PDS_INVITE_REQUIRED: false
      PDS_JWT_KEY_K256_PRIVATE_KEY_HEX: 7efa1db36c2fff216c8c5f6301049d564602f03182bf193b78a90e57229a40f8
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: 4ea86528a570d050d2b70057b554ee90b9c7599bbc1f5bf1730769c043012fa1
      PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX: f8a3f5298d0989f341ac3fd9ba89118aeb7b250d1a824f2717e9384dc12d5337
      PDS_SERVICE_DID: did:web:localhost
      PDS_SERVICE_HANDLE_DOMAINS: .test
      ROCKET_ADDRESS: 0.0.0.0
      READ_NODE_URL: http://firefly-read:40413
      DEFAULT_WALLET_KEY: 6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c
      DEFAULT_WALLET_ADDRESS: 1111EjdAxnKb5zKUc8ikuxfdi3kwSGH7BJCHKWjnVzfAF3SjCBvjh
      DEPLOY_SERVICE_URL: http://firefly:40401
      PROPOSE_SERVICE_URL: http://firefly:40402
      DATABASE_URL: postgresql://postgres@postgresql-rs-1:5432
      PDS_BSKY_APP_VIEW_URL: http://firesky-ts:2584
      ROCKET_PORT: 2583
      PDS_PORT: 2583
    depends_on:
      - postgresql-rs-1
      - minio

  pds-2:
    image: f1r3flyindustries/firesky-rs
    ports:
      - 2683:2683
    env_file:
      - .env-2
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_ENDPOINT: http://minio:9000
      AWS_SECRET_ACCESS_KEY: minioadmin
      PDS_DEV_MODE: true
      PDS_DID_PLC_URL: http://firesky-ts:2582
      PDS_INVITE_REQUIRED: false
      PDS_JWT_KEY_K256_PRIVATE_KEY_HEX: 7efa1db36c2fff216c8c5f6301049d564602f03182bf193b78a90e57229a40f8
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: 4ea86528a570d050d2b70057b554ee90b9c7599bbc1f5bf1730769c043012fa1
      PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX: f8a3f5298d0989f341ac3fd9ba89118aeb7b250d1a824f2717e9384dc12d5337
      PDS_SERVICE_DID: did:web:localhost
      PDS_SERVICE_HANDLE_DOMAINS: .test
      ROCKET_ADDRESS: 0.0.0.0
      READ_NODE_URL: http://firefly-read:40413
      DEFAULT_WALLET_KEY: 6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c
      DEFAULT_WALLET_ADDRESS: 1111EjdAxnKb5zKUc8ikuxfdi3kwSGH7BJCHKWjnVzfAF3SjCBvjh
      DEPLOY_SERVICE_URL: http://firefly:40401
      PROPOSE_SERVICE_URL: http://firefly:40402
      DATABASE_URL: postgresql://postgres@postgresql-rs-2:5432
      PDS_BSKY_APP_VIEW_URL: http://firesky-ts:2684
      ROCKET_PORT: 2683
      PDS_PORT: 2683
    depends_on:
      - postgresql-rs-2
      - minio

  firefly:
    image: f1r3flyindustries/firefly-sky
    command: run -s --validator-private-key=6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c --host firefly --no-upnp --allow-private-addresses --synchrony-constraint-threshold=0.0 --approve-duration 10seconds --approve-interval 10seconds --protocol-port 40400 --discovery-port 40404

  events-init:
    image: f1r3flyindustries/events-sync
    depends_on:
      firefly:
        condition: service_healthy
    restart: no
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - init

  events-listen:
    image: f1r3flyindustries/events-sync
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - listen
      - --communication-service-api-addr=0.0.0.0:8082
      - --sync-api-addr=0.0.0.0:2683
      - --external-hostname=events-listen
      - --extra-sources=ws://pds-2:2683/xrpc/com.atproto.sync.subscribeRepos

  events-push:
    image: f1r3flyindustries/events-sync
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - push
      - --events-source-url=ws://pds-1:2583/xrpc/com.atproto.sync.subscribeRepos
      - --time-threshold=1
      - --size-threshold=16
