services:
  postgresql:
    image: postgres:17-bookworm
    ports:
      - 5434:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  postgresql-2:
    image: postgres:17-bookworm
    ports:
      - 5435:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    profiles:
      - multiple-networks
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    tmpfs:
      - /data
    command: server /data --console-address ":9001"
