services:
  postgresql:
    image: postgres:17-bookworm
    ports:
      - 5434:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  postgresql-2:
    image: postgres:17-bookworm
    ports:
      - 5435:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    profiles:
      - multiple-networks
    command: postgres -c log_statement=all
    tmpfs:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    tmpfs:
      - /data
    command: server /data --console-address ":9001"

  firefly:
    image: ghcr.io/f1r3fly-io/rnode:latest
    ports:
      - 40401:40401
      - 40402:40402
    volumes:
      - ./genesis:/var/lib/rnode/genesis
    command:
      - run
      - -s
      - --no-upnp
      - --allow-private-addresses
      - --synchrony-constraint-threshold=0.0
      - --validator-private-key=6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c

  did-plc:
    image: ihorrr/did-method-plc
    depends_on:
      - postgresql
    environment:
      DB_CREDS_JSON: '{ "password": "", "host": "postgresql" }'
      DB_SCHEMA: plc
      ENABLE_MIGRATIONS: true
      DB_MIGRATE_CREDS_JSON: '{ "password": "", "host": "postgresql" }'
      PORT: 2582

  state-sync-init:
    build:
      context: ..
      dockerfile: docker/state-sync.dockerfile
      args:
        POSTGRESQL_VERSION: 17
    depends_on:
      firefly:
        condition: service_healthy
    restart: no
    profiles:
      - state-sync
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - init

  state-sync:
    build:
      context: ..
      dockerfile: docker/state-sync.dockerfile
      args:
        POSTGRESQL_VERSION: 17
    depends_on:
      firefly:
        condition: service_healthy
      state-sync-init:
        condition: service_completed_successfully
    profiles:
      - state-sync
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - upload
      - --db-url=postgresql://postgres@postgresql:5432
      - --interval=300

  events-init:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
    restart: no
    profiles:
      - multiple-networks
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - init

  events-listen:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 2683:2683
    profiles:
      - multiple-networks
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - listen
      - --communication-service-api-addr=0.0.0.0:8082
      - --sync-api-addr=0.0.0.0:2683
      - --external-hostname=events-listen
      - --extra-sources=ws://host.docker.internal:2999/xrpc/com.atproto.sync.subscribeRepos

  events-push:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    extra_hosts:
      - host.docker.internal:host-gateway
    profiles:
      - multiple-networks
    command:
      - --wallet-key=a8cf01d889cc6ef3119ecbd57301036a52c41ae6e44964e098cb2aefa4598954
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - push
      - --events-source-url=ws://host.docker.internal:2583/xrpc/com.atproto.sync.subscribeRepos
      - --time-threshold=3
      - --size-threshold=16
