[package]
edition = "2024"
name    = "test-transactions-list"
version = "0.1.0"

[dependencies]
dotenv      = { version = "*" }
firefly-api = { workspace = true }
rsky-common = { workspace = true }
rsky-pds    = { workspace = true }
tokio       = { version = "*", features = ["full"] }
